const CartActionTypes = {
  TOGGLE_DROPDOWN_VISIBILITY: "TOGGLE_VISIBILITY",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
};

export default CartActionTypes;
